config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root 'users#my_portfolio'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/friends/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-striped table-hover mt-3">
      <thead>
        <tr>
          <th scope="col">email</th>
          <th scope="col">first name</th>
          <th scope="col">last name</th>
          <th scope="col">actions</th>
        </tr>
      </thead>
      <tbody>
        <% #debugger %>
        <% @friends.each do |friend| %>
          <tr>
            <td><%= friend.email %></td>
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name %></td>

            <td class="col-3">
              <%= link_to 'View Profile', user_path(friend),
                                          class: 'btn btn-sm btn-success me-3' %>
              <%= link_to 'Stop following', friendship_path(friend), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
                                          class: 'btn btn-sm btn-warning' %>
            </td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>