config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root 'users#my_portfolio'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.yh_finance_stock_price(t_symbol)
    require "uri"
    require "net/http"

    url = URI("https://yahoo-finance15.p.rapidapi.com/api/v1/markets/stock/history?symbol=#{t_symbol}&interval=5m&diffandsplits=false")
    # debugger
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true

    request = Net::HTTP::Get.new(url)
    #    request["x-rapidapi-key"] = 'e7f6e7637fmshab60958cd514432p13a37fjsn26bb0feacaee'
    request["x-rapidapi-key"] = Rails.application.credentials.dig(:yahoo_finance_api, :api_key)

    request["x-rapidapi-host"] = "yahoo-finance15.p.rapidapi.com"

    response = http.request(request)

    # Status
    # puts response.code       # => '200'
    # puts response.message    # => 'OK'
    # puts response.class.name # => 'HTTPOK'

    # debugger

    # puts "RESPONSE STATUS: #{response.code}"
    if response.code == "200"
      tmp = JSON.parse(response.read_body)
      if tmp["success"] == false
        nil
      else
        regularMarketPrice = tmp["meta"]["regularMarketPrice"]
        shortName = tmp["meta"]["shortName"]
        longName = tmp["meta"]["longName"]
        new(ticker: t_symbol, name: shortName, last_price: regularMarketPrice)
      end
    end
  end

  def self.finnhub_stock_price(t_symbol)
    require 'finnhub_ruby'

    FinnhubRuby.configure do |config|
      # Rails.application.credentials.dig(:finnhub_api, :api_key)
      config.api_key['api_key'] = 'cvamkq1r01qsapma7mj0cvamkq1r01qsapma7mjg'
    end

    finnhub_client = FinnhubRuby::DefaultApi.new
    puts("===================================================")
    puts(finnhub_client.company_profile2({symbol: 'TEST'}))
    company_profile = finnhub_client.company_profile2({symbol: t_symbol})

    finnhub_client = FinnhubRuby::DefaultApi.new
    company_quote = finnhub_client.quote(t_symbol)
    puts(company_quote)
    puts("===================================================")


    new(ticker: t_symbol, name: company_profile.name, last_price: company_quote.c)
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    # debugger
    @user = current_user
    
    @tracked_stocks = current_user.stocks

    @stock = nil
    if params[:stock].present?
      t_symbol = params[:stock].upcase
      @stock = Stock.finnhub_stock_price(t_symbol)
      # @stock = Stock.yh_finance_stock_price(params[:stock])
      if @stock
        render "users/my_portfolio"
      else
        flash[:alert] = "Symbol not Found"
        redirect_to my_portfolio_path
      end
    else
      flash[:alert] = "Please enter a symbol to search"
      redirect_to my_portfolio_path
    end

    # render json: { ticker: @stock.ticker, name: @stock.name, last_price: @stock.last_price }
  end
end

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-striped table-hover mt-3">
      <thead>
        <tr>
          <th scope="col">ticker</th>
          <th scope="col">name</th>
          <th scope="col">price</th>
          <th scope="col">actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |stock| %>
          <tr>
            <td><%= stock.ticker %></td>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>
            <td class="col-1"><% if current_user.can_track_stock?(stock.ticker) %>
                  <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock.ticker),
                                    class: "btn btn-sm btn-success", data: { turbo_method: :post } %>
                <% elsif current_user.id != @user.id %>
                  <span class="badge badge-secondary">
                    You are already tracking
                    <% if !current_user.under_stock_limit? %>
                      10 stocks
                    <% end %>
                    <% if current_user.stock_already_tracked?(stock.ticker) %>
                      this stock
                    <% end %>
                  </span>
                <% end %>
              <% if current_user.id == @user.id %>
                <%= link_to 'Remove', user_stock_path(stock), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
                                          class: 'btn btn-sm btn-warning' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>