config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root 'users#my_portfolio'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  has_many :friendships
  has_many :friends, through: :friendships
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?    
  end
  
  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end
         
  def self.search(param)
    param.strip! 
    to_send_back = (email_matches(param) + first_name_matches(param) + last_name_matches(param)).uniq
    # debugger
    return nil unless to_send_back
    to_send_back
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    puts "############################## #{current_user.email}"
    @friends = current_user.friends
    # debugger
    if @friends.empty? 
      puts "############################## You have no friends"
    else
      puts "############################## Friends found [#{@friends.count}]"      
    end
  end
  
  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def search
    # debugger
    @user = current_user

    @friends = current_user.friends

    @friends_srch = nil
    if params[:friend].present?
      @friends_srch = User.search(params[:friend])
      # debugger

      
      if !@friends_srch.empty?
        # debugger
        render "users/my_friends"
      else
        flash[:alert] = "No User Found"
        redirect_to my_friends_path
      end
    else
      flash[:alert] = "Please enter a user to search"
      redirect_to my_friends_path
    end

    # render json: { ticker: @stock.ticker, name: @stock.name, last_price: @stock.last_price }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @friends %>
  <div class="card card-header results-block">
    <table class="col-md-12">
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><strong>Name: </strong> <%= friend.full_name %></td>
            <td><strong>Email: </strong> <%= friend.email %></td>
            <td class="col-1"><strong>Actions: </strong> <%= link_to "View Profile", user_path(friend),
                              class: "btn btn-sm btn-success" %>
              <% if current_user.not_friends_with?(friend.id) %>
                <%= link_to 'Follow friend?', friendships_path(friend: friend),
                              class: "btn btn-sm btn-success", data: { turbo_method: :post } %>
              <% else %>
                <span class="badge bg-secondary">
                  You are friends
                </span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'users/friend_result.html' %>'

app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker),
                                    class: "btn btn-sm btn-success", method: :post %>
                                    
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker),
                                    class: "btn btn-sm btn-success", method: :post %>
    <% else %>
      <span class="badge badge-secondary">
        You are already tracking
        <% if !current_user.under_stock_limit? %>
          10 stocks
        <% end %>
        <% if current_user.stock_already_tracked?(@stock.ticker) %>
          this stock
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/my_friends.html.erb
<h1>Friends</h1>
 
 
<div class="search-area mb-2">
  <h3>Search Users</h3>
  <%= form_tag search_friend_path, method: :get, local: true, data: { turbo: false }, class: "mt-3" do  %>
    <div class="form-group row">
      <div class="col-sm-8 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "name or email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding ms-4">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<% if @friends_srch %>
  <% # debugger %>
  <div class="card card-header results-block">
    <table class="col-md-12">
      <tbody>
        <% @friends_srch.each do |friend| %>
          <tr>
            <td>
              <span class="me-3">
                <strong>Name: </strong> <%= friend.full_name %>
                </span>
            </td>

            <td>
              <span class="me-3">
                <strong>Email: </strong> <%= friend.email %>
                </span>
            </td>

            <td>
              <%= link_to "View Profile", user_path(friend),
                              class: "btn btn-sm btn-success ms-3" %>

              <% if current_user.id == friend.id %>

                <span class="badge rounded-pill text-bg-warning ms-3">
                    Your Account
                  </span>
              <% else %>

                <% if current_user.not_friends_with?(friend.id) %>
                  <%= link_to 'Add Friends', friendships_path(user: current_user, friend: friend ),
                                class: "btn btn-sm btn-success ms-3", data: { turbo_method: :post } %>
                <% else %>
                  <span class="badge rounded-pill text-bg-secondary ms-3">
                    You are friends
                  </span>
                <% end %>
              <% end%>

            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<% if !@friends.empty? %>
  <%= render 'friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>pFolio</h1>

<div class="search-area">
  <h3>Search Stocks</h3>

  <%= form_tag search_stock_path, method: :get, local: true, data: { turbo: false } do  %>
    <div class="form-group row">
      <div class="col-sm-8 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Enter Stock Ticker Symbol: i.e. NKE or GOOG", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding ms-4">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<% if @stock %>
  <div class="card card-header results-block mt-3 col-9">
    <span>
      <strong>Symbol:</strong> <%= @stock.ticker %>
    </span>
    <span class="ms-3">
      <strong>Name:</strong> <%= @stock.name %>
    </span>
    <span class="ms-3">
      <strong>Price:</strong> <%= @stock.last_price %>
    </span>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <% if @stock.last_price == 0.0 %>
        <span class="badge rounded-pill text-bg-warning ms-3">
          Stock not found
        </span>
      <% else%>
        <%= link_to 'Add 2 Portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker),
                                class: "btn btn-sm btn-success ms-3", data: { turbo_method: :post } %>
      <% end %>
    <% else %>
      <span class="badge rounded-pill bg-secondary ms-3">
        You are already tracking 
        <% if !current_user.under_stock_limit? %>
          10 stocks
        <% end %>
        <% #debugger %>
        <% if current_user.stock_already_tracked?(@stock.ticker) %>
          this stock
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

<% if !@tracked_stocks.empty? %>
  <%= render partial: 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>


<div class="card card-header results-block mt-3">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td>
          <span class="me-3">
            <strong>Name: </strong> <%= @user.full_name %>
          </span>
        </td>

        <td>
          <span class="me-3">
            <strong>Email: </strong> <%= @user.email %>
          </span>
        </td>
        
        <td>
          <% if current_user.not_friends_with?(@user.id) %>
            <%= link_to 'Follow friend?', friendships_path(friend: @user),
                          class: "btn btn-sm btn-success", data: { turbo_method: :post } %>
          <% else %>
            <% if current_user.id != @user.id  %>
              <span class="badge bg-secondary">
                You are friends
              </span>
            <% else %>
              <span class="badge rounded-pill text-bg-warning ms-2">
                Your Account
              </span>
            <% end%>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list'%>
<% else %>
  <p class='lead mt-3'>This user is not tracking any stocks</p>
<% end %>
<%= link_to 'Back', my_friends_path, class: "btn btn-primary mt-3" %>